ulixee/secret-agent

CHANGELOG.md, client/CHANGELOG.md, client/package.json, core-server/CHANGELOG.md, core-server/package.json, core/CHANGELOG.md, core/package.json, full-client/CHANGELOG.md, full-client/package.json, lerna.json, mitm/CHANGELOG.md, mitm/package.json, package.build.json, package.json, remote-client/CHANGELOG.md, remote-client/package.json, replay-api/CHANGELOG.md, replay-api/package.json, replay-app/CHANGELOG.md, replay-app/package.json, replay/CHANGELOG.md, replay/index.ts, replay/package.json, session-state/CHANGELOG.md, session-state/package.json
We were missing the checksum for mitm and replay-app was being referenced in the published replay, which obviously does not exist in npm.
=> Deployment fixes

replay-app/backend/api/ReplayState.ts, replay-app/backend/api/index.ts, replay-app/frontend/package.json, replay-app/injected-scripts/domReplayer.ts, session-state/api/SessionLoader.ts
This solution is a very temporary way to solve resources not loading up during a realtime replay session. We need a more permanent solution to know when resources are available. I haven't yet been able to figure out what's actually failing to load.
=> fix(replay): fix realtime not loading correctly

core/lib/Tab.ts, full-client/test/tab.test.ts, puppet-chrome/lib/Page.ts, puppet-chrome/lib/Worker.ts
This PR adds the ability to wait for new tabs when a new window is triggered with a delay. The issue was basically a timing problem where the "runIfWaitingForDebugger" command got "stuck" behind setting the command id on the new tab
=> fix(puppet): support new links triggered from ajax

commons/utils.ts, emulator-plugins/shared/injected-scripts/navigator.js, emulator-plugins/shared/injected-scripts/utils.js, full-client/test/emulate.test.ts, injected-scripts/scripts/pageEventsRecorder.ts, puppet-chrome/lib/Frame.ts, puppet-chrome/lib/FramesManager.ts, puppet-chrome/lib/Page.ts, replay-app/backend/Application.ts, replay-app/backend/api/ReplayResources.ts, replay-app/backend/models/PlaybarView.ts, replay-app/backend/models/ReplayView.ts, replay-app/backend/models/Window.ts, replay-app/frontend/src/pages/header/index.vue, session-state/api/SessionLoader.ts
This PR fixes a few issues with replay and some flaky puppet tests:
Replay: 
1 - auto-playing when it's launched.
2 - loading redirected resources
3 - loading svgs that are classified as "Other" resourceType in Chrome
4- upload dom changes if >1 second goes by so we don't have to wait for another command/close to see changes
Random Puppet failures:
- null error stack blowing up some pages
- Permissions overrides are sometimes wrong
=> fix(replay): autostart playback, include redirects

client/index.ts, client/lib/CoreClient.ts, client/lib/CoreCommandQueue.ts, core/index.ts, emulator-plugins/shared/injected-scripts/index.ts, full-client/index.ts, mitm/handlers/BaseHttpHandler.ts, mitm/handlers/HeadersHandler.ts, mitm/handlers/HttpRequestHandler.ts, mitm/lib/MitmRequestAgent.ts, mitm/lib/MitmRequestContext.ts, mitm/lib/Utils.ts, mitm/test/basic.test.ts, mitm/test/http2.test.ts, puppet-chrome/lib/CDPSession.ts, puppet/lib/PipeTransport.ts, puppet/lib/launchProcess.ts, puppet/test/Worker.test.ts, replay-app/backend/models/Window.ts, replay-app/frontend/src/pages/command-overlay/index.vue, replay-app/frontend/src/pages/header/index.vue, replay-app/injected-scripts/domReplayer.ts, session-state/api/index.ts
This PR fixes a few bugs:
Core/Client:
- Don't disconnect and shutdown on "unhandledPromiseRejection" since this doesn't exit the process
- Cancel pending CommandQueue items when we disconnect
Mitm:
- Http2 push headers were improperly handling request/response headers
- Properly handle "lists" of headers (ie, more than 1 entry)
- Don't manipulate http2 headers to look like http1 headers - we didn't have the http2 server flag set in time for this call
Replay:
- Hide replay elements using a shadow dom
- Reset navigation when going back and then selecting a new "replay" to view.
=> Http2 Bug Fixes; Don't shutdown on UnhandledRejection

full-client/test/emulate.test.ts, mitm/handlers/CacheHandler.ts, mitm/handlers/HeadersHandler.ts, mitm/handlers/HttpRequestHandler.ts, mitm/lib/MitmRequestAgent.ts, mitm/test/basic.test.ts
Also catch h2 push streams closing/errors
This PR catches some bugs we had in http2 handling. Most notably, a closed push stream could kill the process
=> fix(mitm): don’t send duplicated headers to h2

client/index.ts, client/lib/CoreClient.ts, core/index.ts, session-state/test/api.test.ts, testing/helpers.ts
Don't shutdown client when there's an unhandled promise rejection, but still log them.
=> fix(core): dont close client on promise rejections

client/lib/AwaitedEventTarget.ts, client/lib/Browser.ts, client/lib/Interactor.ts, client/lib/Request.ts, client/lib/SetupAwaitedHandler.ts, client/lib/Tab.ts, client/package.json, core-interfaces/AwaitedDom.ts, core-interfaces/package.json, core/package.json, full-client/package.json, full-client/test/document.test.ts, full-client/test/emulate.test.ts, injected-scripts/scripts/jsPath.ts, mitm/test/basic.test.ts, website/package.json, yarn.lock
Add support for awaited dom features:
- Convert AwaitedHandler to use delegate pattern
- Xpath support (we now loop through all parameters for methods and convert to awaitedPath as necessary)
- JsPath - re-inflate paths in parameters
- Export Node and XPathResult from core-interfaces so you can access the static properties (eg, XPathResult.ANY_TYPE)
- Support for more restrictive type checking on StateMachine
=> feat(client): xpath support, array index access

client/lib/SetupAwaitedHandler.ts, core/index.ts, core/lib/Session.ts, core/lib/Tab.ts, core/test/location.test.ts, full-client/test/emulate.test.ts, mitm/test/http2.test.ts, puppet-chrome/lib/NetworkManager.ts, puppet-chrome/lib/Page.ts, puppet/interfaces/IPuppetNetworkEvents.ts, session-state/index.ts, session-state/lib/TabNavigations.ts
This PR changes a few things:
1) Connect redirects to navigations after the initial one (ie, new link, new tab)
2) waitForNewTab waits for an initial resource to be loaded - this is so that location "Change" events will not trigger for the first page loaded in a new tab.
=> fix(core): wait for location change on new tab

client/index.ts, commons/Timer.ts, core/lib/Tab.ts, puppet-chrome/lib/Frame.ts, puppet-chrome/lib/FramesManager.ts
This PR fixes some bugs found while running Double Agent tests.
1) Default handling shutdown in Secret Agent if settings are provided but no handleShutdownSignals/captureUncaughtClientErrors option
2) Shutdown waitForElement handlers when SecretAgent is interrupted (was waiting full 30 seconds on kill).
3) If a tab keeps the same frameid but navigates to new urls, contextIds are occasionally reused. This was causing an incorrect contextId to be used for "evaluate" commands.
=> fix(puppet): incorrect reuse of executionContextId

client/interfaces/ISecretAgentClass.ts, emulate-browsers/base/injected-scripts/MediaRecorder.isTypeSupported.ts, emulate-browsers/base/lib/modifyHeaders.ts, emulate-browsers/chrome-80/index.ts, emulate-browsers/chrome-83/index.ts, emulate-browsers/safari-13/index.ts, website/docs/BasicInterfaces/SecretAgent.md, website/docs/Overview/Configuration.md
- Quality score is removed from locale property of emulators
- accept-language header bypasses using default values from DA json if emulator's locale has been set
- MediaRecorder.isTypeSupported correctly accepts the type arg
- SecretAgent.configure now accepts all properties of Core.configure
- Updated website docs
=> fix: emulators were failing some double-agent tests

emulate-browsers/base/injected-scripts/_proxyUtils.ts, emulate-browsers/base/test/iframe.test.ts, mitm/handlers/HeadersHandler.ts, mitm/handlers/HttpRequestHandler.ts, mitm/lib/MitmRequestAgent.ts, puppet-chrome/lib/BrowserContext.ts, puppet-chrome/lib/Page.ts
Fixes bugs from #111 
- capitalized http2 headers cause us to copy a header 2x that can only exist once in an http2 response
- mitm is checking certificates for validity and golang doesn't like the Commodo certs, so throwing up on a mac. Turned off certificate checking by default, even though long term, this creates a hole we'll want to plug
=> Http2 bug fix

emulate-browsers/base/injected-scripts/_proxyUtils.ts, emulate-browsers/base/test/iframe.test.ts, puppet-chrome/lib/BrowserContext.ts, puppet-chrome/lib/Page.ts
Fixes 2 small bugs:
1) creepjs #108 was detecting a diff in toString across frames
2) worker devtools api calls weren't tracking to the correct session db during creation
=> Emulator Fixes

client/index.mjs, client/index.ts, full-client/index.mjs, full-client/index.ts, session-state/api/SessionLoader.ts
This PR adds exports to the client libs for constants and enums that you might want to pass into our apis.
=> feat(client): export required enums and consts

core/lib/Tab.ts, emulate-humans/ghost/index.ts, injected-scripts/scripts/jsPath.ts
This PR has 3 small bug fixes:
1. Nesting commands in the new core/Tab structure causing issues double-counting commands
2. elementIsVisible was not properly checking if elements were "on screen"
3. ghost human emulator causing a lot of excess scrolls that were trying to scroll to negative positions (ie, -26px)
=> Bug fixes: isVisible fix, scroll below 0 fix, nested commands fix

client/lib/Agent.ts, client/lib/ScriptInstance.ts, client/test/basic.test.ts
This PR fixes two issues:
1 - don't connect to an agent just to disconnect
2 - handle capturing errors connecting and throw them only when a connection is requested (this is using our funky delayed-connect process that allows a default agent to exist without connecting until it's actually used)
=> fix(client): error handling for session connect

client/connections/CoreClientConnection.ts, client/connections/RemoteCoreConnection.ts, client/package.json, commons/SqliteTable.ts, commons/package.json, core/lib/RemoteServer.ts, core/package.json, core/test/remote.test.ts, replay/backend/api/index.ts, replay/package.json, session-state/api/SessionLoader.ts, session-state/api/index.ts, session-state/api/sendSessionOverWs.ts, session-state/interfaces/ISessionReplayServer.ts, session-state/package.json, session-state/test/api.test.ts, website/docs/Advanced/Remote.md, yarn.lock
This PR moves the Core Api and Replay Api to use websockets instead of http2/json-socket.
=> Convert RemoteServer/Client and Replay API to use Web Sockets

client/package.json, core/lib/GlobalPool.ts, full-client/test/interact.test.ts, mitm-socket/index.ts, mitm/lib/MitmRequestAgent.ts, puppet-chrome/index.ts, puppet-interfaces/IPuppetLauncher.ts, puppet/index.ts, puppet/lib/BrowserFetcher.ts, puppet/lib/browserPaths.ts, puppet/lib/launchProcess.ts, puppet/package.json, puppet/test/launchProcess.test.ts, replay/backend/Application.ts, replay/backend/api/ScriptRegistrationServer.ts, replay/backend/api/index.ts, replay/index.ts, replay/install/Utils.ts, replay/install/index.ts, replay/package.dist.json, replay/package.json, yarn.lock
This PR addresses a few things with our external dependencies:
*Replay*
- Replay now has single install for all core versions in a project (the newest will be installed)
- Replay lives in the same directory as the Chrome engines
- Replay locks on files to create a path to an api server where scripts register. This prevents the electron bug for popping up so many processes to try to determine if a new one should launch. Scripts now register over http calls instead
*Puppet:*
- Clean up sandbox errors (copied from playwright)
- Better error handling if a chrome version is not installed (previously was showing an ENOENT error without explicitly saying what was happening)
- Puppet engines share a common directory inside app cache (secret-agent)
=> Single Replay, Shared Directory withe Browsers, Better Launch errors

puppet-chrome/index.ts, session-state/models/ResourcesTable.ts
Chrome 80 and 81 had an experimental "OutOfBlinkCors" feature that meant certain requests never registered a Preflight inside of devtools. Disabled this feature.
=> fix(mitm): preflight requests not always sent

core/test/user-profile.test.ts, emulate-browsers/base/injected-scripts/_proxyUtils.ts, emulate-browsers/safari-13/index.ts
Safari has specific handling around cookies that didn't really have anything exercising page triggered cookies. Tweaked the test to make sure we hit this code branch, and fixed the error.
NOTE: this has a todo for you @calebjclark to inject either a sessionid or a logger to the emulators. I thought doing too much in here in this PR might break your stuff.
=> fix(emulators): safari cookie handling fix

client/lib/Agent.ts, client/lib/CoreTab.ts, client/lib/Tab.ts, commons/Timer.ts, copy-dist.js, core/lib/LocationTracker.ts, core/lib/Tab.ts, core/test/location.test.ts, core/test/tab.test.ts, full-client/test/websocket.test.ts, package.json, prepare-dist.js, puppet-chrome/lib/Page.ts, puppet-interfaces/IPuppetPage.ts, replay/backend/Application.ts, replay/backend/api/index.ts, replay/bin.ts, replay/index.ts, replay/install/Utils.ts, replay/package.json, replay/tsconfig.dist.json, replay/tsconfig.json, website/docs/BasicInterfaces/Agent.md, website/docs/BasicInterfaces/Tab.md
This PR adds a few small features:
- goto, goBack, goForward all have optional timeoutMs params. Default to 30 seconds. 0 will clear out any timeout
- Tab.reload: ability to trigger a reload
- Replay will now load from a local dist build if present (order of precedence is 1) local build, 2) monorepo, 3) binary
- Replay has a "bin" that will be distributed with replay, so you can run `yarn replay` from anywhere you've installed secret-agent/replay (note: this will work from the build directory, but not the top level of the monorepo). It opens to the dashboard and loads up a default node-path so it can launch core
Closes #112
=> Timeouts, Replay Bin, Reload

core/lib/Tab.ts, full-client/test/basic.test.ts
Adding messages directing users how to set cookies before a page has loaded.
fix for #142
=> feat(core): friendly message setting cookies

client/lib/Handler.ts, commons/TypeSerializer.ts
Revives stack traces for errors instead of using a typeson, confusing stack. If Core is not running in a "child process", also log unhandled errors locally.
=> fix(client): fix reviving stack traces in typeson

core/lib/Interactor.ts, core/lib/Tab.ts, core/test/interact.test.ts, core/test/navigation.test.ts, examples/ulixee.org.ts, puppet-chrome/lib/Browser.ts, puppet-chrome/lib/BrowserContext.ts, puppet-chrome/lib/CDPSession.ts, puppet-chrome/lib/Connection.ts, puppet-interfaces/IConnectionCallback.ts, puppet-interfaces/IPuppetConnection.ts, puppet-interfaces/IPuppetEngine.ts, puppet-interfaces/IPuppetWorker.ts, puppet/lib/PipeTransport.ts, puppet/test/Worker.test.ts, website/docs/Advanced/Remote.md
Fixes 2 issues:
1) If you open multiple windows (or links have not cleaned up old ones yet), you can end up with an "opener" of a popup being another regular window. This means closing can have weird effects (like in the Page.popups tests that occasionally failed for this reason)
2) If the page navigates out under you, we need to cancel pending interactions
=> Timeout mouse

emulate-browsers/base/lib/DomDiffLoader.ts, emulate-browsers/base/lib/VersionUtils.ts, emulate-browsers/base/test/VersionUtils.test.ts
This fixes #166. The emulator data is tagged to version 11, but the OS version was 11.2. It should fallback to 11 if no 11.2 exists.
=> fix: os version should fallback to major if no minor exists

client/connections/ConnectionToCore.ts, client/connections/DisconnectedFromCoreError.ts, client/connections/RemoteConnectionToCore.ts, client/lib/CoreCommandQueue.ts, client/lib/CoreSessions.ts, client/lib/CoreTab.ts, client/lib/Handler.ts, commons/Queue.ts, commons/Timer.ts, core/lib/CoreProcess.ts, core/server/ConnectionToClient.ts, core/server/index.ts, full-client/test/handler.test.ts, mitm/handlers/RequestSession.ts, mitm/lib/Dns.ts, mitm/lib/MitmRequestAgent.ts, mitm/test/dns.test.ts, publish.sh, website/docs/BasicInterfaces/Handler.md
This PR has a main feature to go alongside Handler.waitForAllDispatches, called waitForAllDispatchesSettled. It differs from waitForAllDispatches in that it will run through ALL dispatches and return the results of each at the end, instead of short-circuiting at the first thrown error. This feature is based on some of the ways waitForAllDispatches is being used in MissionImpossible, as well as in #165 #172 examples from @A-PostHuman.
As part of this PR, some of the inner workings of CoreCommandQueue and CoreConnections got cleaned up to consistently return errors - whichever part of the process you're in. We still had some timing problems if a connection was not yet in-flight at the time of disconnect.
Two bug fixes are added to this PR:
1. Dns errors were bubbling up because of our …
=> Wait for all dispatches settled

commons/SourceMapSupport.ts, core/dbs/SessionDb.ts, core/lib/SessionState.ts, core/lib/Tab.ts, core/lib/TabNavigations.ts, core/lib/TabNavigationsObserver.ts, core/package.json, core/test/navigation.test.ts, mitm/handlers/BaseHttpHandler.ts, mitm/handlers/HttpRequestHandler.ts, mitm/handlers/HttpUpgradeHandler.ts, mitm/lib/MitmProxy.ts, mitm/lib/MitmRequestAgent.ts, mitm/test/http2.test.ts, puppet-chrome/lib/NetworkManager.ts
- Mitm could throw unhandled errors during write if the stream got closed
- Tab DomContentLoaded can take a really long time if you loop and re-load in the same tab a lot of times. Extended the timeout to 60 seconds
=> Timeout bugs

core/lib/SessionState.ts, core/lib/Tab.ts, puppet-chrome/lib/Browser.ts, puppet-chrome/lib/BrowserContext.ts, puppet-chrome/lib/Frame.ts, puppet-chrome/lib/FramesManager.ts, puppet-chrome/lib/Page.ts, puppet-interfaces/IPuppetPage.ts
We were simply ignoring if a page crashed and no further commands were working. This PR makes sure we actually throw errors when we can't run things anymore.
=> fix(puppet): handle crashed windows

mitm/lib/MitmRequestContext.ts, mitm/test/http2.test.ts
Valid urls were failing to parse (ie, a url ending in //)
=> fix(mitm): some WHATWG urls failing to parse

commons/SessionClosedOrMissingError.ts, commons/TypeSerializer.ts, commons/interfaces/IPendingWaitEvent.ts, commons/interfaces/TimeoutError.ts, commons/package.json, commons/test/TypeSerializer.test.ts, core/lib/DomRecorder.ts, core/lib/FrameNavigationsObserver.ts, core/lib/InjectedScripts.ts, core/lib/Session.ts, puppet-chrome/lib/Frame.ts, puppet-chrome/lib/Worker.ts, puppet-interfaces/IPuppetFrame.ts, website/docs/Advanced/UserProfile.md, yarn.lock
This PR adds a type serializer for JSON and replaces typeson. It's not as full featured, but doesn't require corejs and regenerator runtime as dependencies. It's also smaller to send over to the js side.
=> chore(core): type serializer

core/lib/GlobalPool.ts, emulate-browsers/base/injected-scripts/navigator.ts, puppet/index.ts, puppet/lib/launchProcess.ts
Calls to clearAppBadge and setAppBadge were crashing Puppet/Chrome. It's a known issue in headless, that appears to be resolved in chrome 89 (https://chromium.googlesource.com/chromium/src.git/+/c8a9fc64753d988e7ee59045a52aea14773fbe0d)
As part of this, I'm proposing we log Chrome stdout and stderr to the database by default, not with additional logging. It was hard to find our crash issue without it.
=> fix(emulator): polyfill setAppBadge/clearAppBadge

core/lib/Tab.ts, mitm-socket/lib/connect.go, mitm-socket/lib/domain_socket_piper.go, mitm-socket/test/MitmSocket.test.ts, mitm/handlers/HttpRequestHandler.ts, mitm/lib/MitmRequestAgent.ts, mitm/lib/MitmRequestContext.ts, puppet-chrome/lib/NetworkManager.ts
This PR fixes a few network errors:
1. URLs starting with "ws" (like wsj.com) were being treated as if they were starting with ws://, ie websockets.
2. Some sites send redirect and end over http. The golang sockets were not correctly reading these
3. The golang socket library was not properly disconnecting with a 0 byte EOF
4. Sites that redirect to a protocol (ie, whatsapp://chat) were failing to ever trigger paintingStable
=> Network Issues

core-interfaces/IBrowserEngine.ts, core/index.ts, core/lib/GlobalPool.ts, emulate-browsers/base/index.ts, emulate-browsers/base/injected-scripts/navigator.ts, emulate-browsers/chrome-80/index.ts, emulate-browsers/chrome-81/index.ts, emulate-browsers/chrome-83/index.ts, emulate-browsers/safari-13/index.ts, full-client/test/detection.test.ts, puppet-chrome/index.ts, puppet/index.ts
This PR helps avoid widevine checks from uncovering SecretAgent by:
1) If headless, polyfiling requests to widevine (NOTE: this will not actually play widevine content)
2) If non-headless, allow regular widevine operation (fixed by removing "disable-update-components" in chrome, which flagged off widevine.
As part of this PR, control of whether a browser is headless is moved closer to the BrowserEmulators control. Right now, they all use the same env variable, but we could easily change that to be unique per browser engine.
NOTE: this PR adds to the emulator scripts, but has to actually add a variable to the navigator script, so will need to be updated in the "template" in slab.
=> fix(emulate): mask widevine checks

core/lib/Session.ts, mitm/lib/BrowserRequestMatcher.ts
If an http response is returned to the mitm and we don't match a tab (ie, Chrome requested the resource), we were throwing out the data. This PR broadcasts it on the first active tab by default instead.
=> fix(mitm): store resources if tab not found

core-interfaces/IElementRect.ts, core-interfaces/IInteractionsHelper.ts, core/lib/CommandFormatter.ts, core/lib/Interactor.ts, emulate-humans/ghost/index.ts
When running interactions, if you pass in a query selector, we run it multiple times _within_ a single interaction. This can have strange effects if, for instance, nodes swap order, as it does in many cases where modals pop up. So you can end up trying to move and click on different nodes in the same interaction. 
This PR "pegs" the nodeid for the course of a single interaction.
In addition, if an element cannot be clicked on, a bit more information is presented about what could be going on.
=> feat(interact): peg nodeid for interactions

core/lib/GlobalPool.ts, puppet-chrome/index.ts, puppet/index.ts
The current flags we have turned on for GPU are disabling gpu and gpu compositing on Macs, Windows and Linux. I think we originally turned the flags on this way to that a docker/machine with no gpu would run the same way as a development machine. The problem is some sites (like https://github.com) with a lot of webgl are incredibly slow when you do that.
I'm proposing (not 100% sure on this) that we should NOT disable gpu by default. NOTE that disable gpu was a workaround for old chromium issues that made gpu not work in headless on win/mac/linux even when there was hardware present (https://crbug.com/737678 and https://crbug.com/729961). Those are resolved at this point, so it's really just about working with no gpu. 
There's also a potential issue with Linux headless using acceleration …
=> fix(puppet): remove disable-gpu flag

client/package.json, core-interfaces/package.json, core/lib/CommandFormatter.ts, core/lib/Interactor.ts, core/package.json, core/test/interact.test.ts, full-client/package.json, full-client/test/document.test.ts, full-client/test/interact.test.ts, website/package.json, yarn.lock
- Fix re-hovering over a location that is already hovered.
- Update Awaiteddom to return null if a node doesn't exist
- Show non-interacted nodes in replay that are used in execJsPath
Closes #209
=> Re-Hover, Null Elements

core/lib/FrameNavigationsObserver.ts, core/models/FrameNavigationsTable.ts, emulate-browsers/base/test/iframe.test.ts
We have some sites in MI that never trigger waitForPaintingStable. They do get the load event. In the top 100 sites, load and content stable occur within 1ms of each other for most sites, within 24ms worst case. This fallback clause will cover these within a large margin of error.
=> feat(emulate): wait 3 seconds after load

commons/eventUtils.ts, core-interfaces/INavigation.ts, core-interfaces/ITypedEventEmitter.ts, core/lib/FrameEnvironment.ts, core/lib/FrameNavigations.ts, core/lib/Session.ts, core/lib/Tab.ts, core/models/FrameNavigationsTable.ts, core/test/navigation.test.ts, emulate-browsers/base/test/chrome.test.ts, emulate-browsers/base/test/plugins.test.ts, emulate-browsers/base/test/utils.test.ts, puppet-chrome/lib/Frame.ts, puppet-chrome/lib/FramesManager.ts, puppet-chrome/lib/NetworkManager.ts, puppet-chrome/lib/Page.ts, puppet-interfaces/IPuppetFrame.ts, puppet-interfaces/IPuppetNetworkEvents.ts, puppet-interfaces/IPuppetPage.ts, puppet/test/Frames.test.ts, puppet/test/Page.navigate.test.ts, puppet/test/Page.popups.test.ts, puppet/test/Page.test.ts, puppet/test/TestPage.ts, puppet/test/load.test.ts
We had some github actions failing under load under Chrome 88 because of the way things have changed with new tabs. Trying to fix it, I realized we were taking all frame "navigation" changes as if they will always come in perfect order. This could cause issues sometimes where we would mis-match the redirect urls or current navigation that was actually an event updating a previous navigation.
In this PR, I've moved to tracking navigations by the "loader id" assigned in chrome.
=> Improve FrameNavigation tracking

client/index.mjs, core/index.mjs, examples/handler.mjs, full-client/index.mjs
Named MJS exports only work when they're explicit.
Close for #221
=> fix(client): explicit mjs exports

core/lib/FrameEnvironment.ts, full-client/test/fetch.test.ts, website/docs/BasicInterfaces/FrameEnvironment.md, website/docs/BasicInterfaces/Tab.md
If a fetch is run on a page with no "goto", it currently fails. This PR throws an error if a url hasn't been loaded for a frame, and tweaks the documentation.
=> feat(core): throw fetch error if no origin

client/lib/CoreCommandQueue.ts, client/lib/SetupAwaitedHandler.ts, full-client/test/document.test.ts, jest.setupPerTest.js, puppet-chrome/lib/DevtoolsSession.ts
This PR just adds a test for awaiting xpath result nodes. We needed to ensure we were serializing any jspath args in general, so this adds that capability.
Resolves #239
=> feat(client): allow awaiting xpath

client/lib/ResourceResponse.ts, emulate-browsers/base/lib/modifyHeaders.ts, mitm-socket/index.ts, mitm-socket/install.js, mitm/lib/MitmRequestAgent.ts
1. Fix mitm/install.js for 32 bit windows installs
2. Reuse http2 connections when they resolve to the same host
3. Don't blow up if no http response is returned
Resolves #241
=> fix(mitm): fix install script, reuse same h2 conn

mitm-socket/index.ts, mitm/lib/Dns.ts, mitm/lib/DnsOverTlsSocket.ts, mitm/test/dns.test.ts
If an EOF is received from the dns socket, we need to try to reconnect
=> fix(dns): handle dns socket disconnect

client/lib/Interactor.ts, core/lib/Session.ts, core/lib/SessionState.ts, core/lib/Tab.ts, core/models/ResourcesTable.ts, core/test/resources.test.ts, full-client/test/interact.test.ts, mitm/lib/DnsOverTlsSocket.ts, mitm/test/dns.test.ts
Right now, if you pass in `interact({ move: element }, 'click')`, as per the examples, the second command tries to click at 0,0. This PR fixes the last location passed in.
In addition, this fixes some stability issues with tests
=> Interactor should be able to provide string commands, like examples

.github/workflows/lint-and-test.yml, commons/downloadFile.ts, copyfiles.js, mitm-socket/install.js, mitm-socket/lib/BaseIpcHandler.ts, mitm-socket/package.build.json, mitm-socket/package.json, replay/install/index.ts, replay/package.dist.json, replay/package.json
This PR adds proxy checking to the replay and mitm downloads. It also throws a more informative error when the mitm-socket was not installed
Closes #261 #262
=> fix(mitm): proper errors when mitm binary missing

core/index.ts, core/lib/Plugins.ts, core/lib/Session.ts, plugins/execute-js/test/dependencies.test.ts
ClientExtender plugins are allowed to specify an array of CoreExtender plugin IDs that it requires (see execute-js-plugin). However, those same CoreExtender plugins must be installed in Core. This can be frustrating/difficult since by default the Core is started automatically and in another process -- therefore, the developer has no easy access to adding the CoreExtender through Core.use().
This PR allows Core to automatically require the CoreExtender so long as it available through the node require. As a security precaution it checks to ensure the package is actually a CoreExtender.
Also, Core now includes a allowDynamicPluginDependencies static property that can be set to false (but is true by default). Setting this property to false disables the ability to dynamically require these …
=> feat: dynamically require core extender plugins required by client

core/injected-scripts/domReplayer.ts, replay/backend/api/ReplayTabState.ts, replay/injected-scripts/domReplayerSubscribe.ts, website/docs/BasicInterfaces/FrameEnvironment.md, website/docs/Overview/Configuration.md
We were sometimes loading iframes too quickly in replay, which made them not display properly because the HEAD/HTML elements weren't ready yet.
Also added a message to replay startup to make it clear what is being viewed.
Closes #270
=> Fix iFrames not always rendering in Replay

core/injected-scripts/MouseEvents.ts, core/lib/Interactor.ts, plugins/default-human-emulator/index.ts
Improves the messages when a dom node can't be hovered prior to clicking.
=> feat(core): improve mouse message when not there

client/connections/ConnectionToCore.ts, client/lib/Agent.ts, client/lib/FrameEnvironment.ts, core/injected-scripts/MouseEvents.ts, core/injected-scripts/domReplayer.ts, core/injected-scripts/interactReplayer.ts, core/injected-scripts/jsPath.ts, core/interfaces/ICommandWithResult.ts, core/interfaces/ISerializable.ts, core/lib/FrameEnvironment.ts, core/lib/Interactor.ts, core/lib/JsPath.ts, core/lib/SessionState.ts, core/models/FocusEventsTable.ts, core/models/MouseEventsTable.ts, core/models/ScrollEventsTable.ts, core/server/ConnectionToReplay.ts, core/test/detach.test.ts, full-client/test/interact.test.ts, interfaces/IWindowOffset.ts, plugins/default-human-emulator/index.ts, replay/backend/api/ReplayTabState.ts, replay/backend/api/ReplayTick.ts, replay/backend/api/index.ts, replay/backend/models/ReplayView.ts, replay/shared/interfaces/ICommandResult.ts, replay/shared/interfaces/ISaSession.ts
Prior to this fix, you couldn't pass nested frame elements to click/interact. Issues:
- Was assuming all elements were in main frame
- Didn't account for the frame offset in interaction functions (mouse over, mouse verified, etc)
- Didn't replay correctly
=> fix(core): fix interact with elements in iframes

plugins/default-browser-emulator/lib/helpers/configureBrowserLaunchArgs.ts, puppet/lib/launchProcess.ts
When running "headed", if the data directory is not cleaned up, it could result in not being able to launch a second time.
=> fix(puppet): clean data dir on close

plugins/execute-js/lib/ClientPlugin.ts, plugins/execute-js/secret-agent-mods.d.ts, plugins/execute-js/test/basic.test.ts
Solves  #281. Args can now be passed into `agent.executeJs`.
=> feat: args can now be passed into ExecuteJsPlugin

plugins/default-browser-emulator/lib/BrowserData.ts, plugins/default-browser-emulator/lib/VersionUtils.ts, plugins/default-browser-emulator/lib/utils/getLocalOperatingSystemMeta.ts, plugins/default-browser-emulator/test/VersionUtils.test.ts
BrowserData now uses the same mac os version converter as getLocalOperatingSystemMeta.ts, which had been correctly converting 11.x to just 11.
=> fix: useragent was not correctly parsing mac os 11

core/lib/GlobalPool.ts, core/lib/Tab.ts, interfaces/IViewport.ts, plugins/default-browser-emulator/index.ts, plugins/default-browser-emulator/lib/Viewports.ts, plugins/default-browser-emulator/lib/helpers/configureBrowserLaunchArgs.ts, plugins/default-browser-emulator/lib/helpers/setScreensize.ts, puppet/lib/launchProcess.ts, puppet/test/_CustomBrowserEmulator.ts, website/docs/Advanced/Session.md, website/docs/BasicInterfaces/Agent.md, website/docs/BasicInterfaces/Handler.md, website/docs/BasicInterfaces/Interactions.md, website/docs/Help/troubleshooting.md, website/docs/Overview/BasicConcepts.md, website/docs/Overview/Configuration.md
This PR cleans up the headed browsers to match the configured viewports. Also fixes a few random documentation issues.
other:
- rmdir is deprecated in node 16 (now just rm)
- default the "scale" property when passing a rectangle to screenshot
=> fix(core): fix headed browser size/viewport docs

commons/SqliteTable.ts, core/connections/ConnectionToClient.ts, core/injected-scripts/interactReplayer.ts, core/injected-scripts/jsPath.ts, core/injected-scripts/pageEventsRecorder.ts, core/lib/CommandRecorder.ts, core/lib/DetachedTabState.ts, core/lib/FrameEnvironment.ts, core/lib/InjectedScripts.ts, core/lib/Session.ts, core/lib/SessionState.ts, core/lib/Tab.ts, core/models/CommandsTable.ts, core/models/SessionTable.ts, core/test/sessionResume.test.ts, examples/.gitignore, examples/server.ts, examples/sessionResume.ts, interfaces/ICommandMeta.ts, interfaces/ISessionCreateOptions.ts
This feature enables us to keep alive a Chrome session and resume it.
In headed, we include user interactions and a bar showing your current command (so you can see the changes happening).
SessionResume works by comparing the sequence of commands you provide to a previous run. If we can pick up where you left the browser, we ONLY play the new commands. This helps you to build out a new script without constantly running from the beginning.
Here are the different ways SessionResume works (arguments):
- sessionId: 
- if kept alive, it will resume the current browser context based on the start location
- if closed, will load the session attributes from the db and recreate it with the same settings
- startLocation: where to resume commands
- currentLocation: tries to run with as many commands …
=> feat(core): keepalive and resume a session

client/lib/Resource.ts, client/lib/WebsocketResource.ts, core/lib/SessionState.ts, core/lib/UserProfile.ts, core/models/ResourcesTable.ts, core/test/user-profile.test.ts, interfaces/IResourceMeta.ts, mitm/handlers/RequestSession.ts, mitm/lib/MitmRequestContext.ts, plugins/default-human-emulator/index.ts, puppet-chrome/lib/ProtocolError.ts, puppet/lib/PuppetLaunchError.ts, website/docs/Advanced/Resource.md, website/src/layouts/partials/Header.vue
1. Record the document url of each resource and make available via resources api (#362)
2. Fix stack trace for protocol errors (they were empty)
3. Occasional mouse errors in human emulator due to target rect moving but not updating the target point to be inside the modified rect (ie, mouse moves and scrolls, but the point is not updated to be where the element now is)
4. Make sure to keep around old storage if an origin isn't loaded
=> Various small bug fixes

core/lib/CorePlugins.ts, core/lib/Session.ts, full-client/test/basic.test.ts, interfaces/ICorePlugin.ts, interfaces/IHttpSocketAgent.ts, interfaces/IHttpSocketConnectOptions.ts, interfaces/IHttpSocketWrapper.ts, interfaces/ISessionCreateOptions.ts, mitm-socket/index.ts, mitm/lib/MitmRequestAgent.ts, plugins/default-browser-emulator/index.ts, plugins/default-browser-emulator/injected-scripts/webrtc.ts, plugins/default-browser-emulator/lib/helpers/lookupPublicIp.ts, plugins/default-browser-emulator/package.json, plugins/default-browser-emulator/test/publicIp.test.ts, website/docs/BasicInterfaces/Agent.md, website/docs/BasicInterfaces/Handler.md
This PR adds a capability to mask public ips when using a proxy. The current Chrome settings do not seem to take in our versions of Chrome. 
The feature works by modifying the dom properties to hide the proxy IP. Part of the Chrome team's challenge is that UDP over proxies is very difficult to support. WebRTC might be slightly easier, but still tough.
A user can pre-provide their proxy ip, public ip and/or an IP Lookup Http Service. If none are provided the default browser emulator will use the ipify to mask the user's public ip if using a proxy url.
=> feat(plugins): mask public ip in webrtc

commons/Logger.ts, plugins/default-browser-emulator/lib/BrowserData.ts, plugins/default-browser-emulator/lib/DataLoader.ts, plugins/default-browser-emulator/lib/VersionUtils.ts, plugins/default-browser-emulator/lib/helpers/selectUserAgentOption.ts, plugins/default-browser-emulator/test/selectUserAgentOptions.test.ts
The user agent selector has a few holes that are plugged by this PR.
1. The default example in the docs `~mac and chrome >90` did not work
2. If you had multiple selectors (ie, OS and browser, it would take matches of "either/or", which was not what we wanted)
3. There are issues if you use an OS we don't know about.
4. We needed default selectors if you don't provide an operator (=) or version (*)
Closes #369 and causes #371 to emit a better error, but we probably need to follow up with some kind of actual option to use a mobile user agent on a default browser.
=> fix(plugins): improve user agent selector

client/lib/Agent.ts, client/lib/CoreCommandQueue.ts, client/lib/CoreFrameEnvironment.ts, client/lib/CoreTab.ts, client/lib/FrameEnvironment.ts, client/lib/Tab.ts, core/lib/FrameEnvironment.ts, core/lib/FrameNavigationsObserver.ts, core/lib/Tab.ts, core/test/navigation.test.ts, full-client/test/waitForLocation.test.ts, interfaces/IInteractions.ts, plugins/default-human-emulator/index.ts, website/docs/BasicInterfaces/FrameEnvironment.md, website/docs/BasicInterfaces/Tab.md
This PR introduces two small, but potentially impactful changes:
1) The "waitForReady" state inside core is changed from DomContentLoaded to HttpResponded for the current resource. It seems like a potentially expensive condition to impose on some sites that take a long time to load. 
NOTE: I kept interact and execJsPath as requiring DomContentLoaded before running. Things seemed fragile in our tests without it, which made me question when you'd really not want it for those two. Up for conversation about this.
2) Two core commands are now going to "bypass" the coreCommandQueue "line" and run outside the regular queue: getResourceProperty and dismissDialog. Both are used inside event listeners, and in the case of getResourceProperty, it can't really impact the flow of the script
This PR …
=> feat(core): dialogs should run out of command line

core/lib/FrameNavigations.ts, core/lib/Session.ts, core/lib/Tab.ts, full-client/test/waitForLocation.test.ts
Bug reported by user: after a form submission that redirects in-page "before the resource is loaded" will never resolve the resource, so the location change hangs.
=> fix(core): in page nav not resolving resource

client/lib/CoreCommandQueue.ts, core/server/ConnectionToClient.ts, full-client/test/detach.test.ts
Ensure all detached records and output are truly flushed before disconnecting.
=> fix(client): wait for all command queue flushes

mitm-socket/package.build.json, plugins/default-browser-emulator/lib/helpers/lookupPublicIp.ts
When we added a public ip lookup, we had it using http urls for speed. The problem is an http proxy can't do CONNECT to non-secure urls, so it was failing to lookup the public ip. We have a flaw in the system that an http url won't work over our current http proxy system. For now, I've changed the public IP lookups to just use https urls
=> fix(mitm): lookup public ip should use https

core/injected-scripts/domStorage.ts, core/injected-scripts/indexedDbRestore.ts, core/lib/InjectedScripts.ts, core/lib/Session.ts, core/lib/UserProfile.ts, core/test/user-profile.test.ts, full-client/test/filechooser.test.ts, mitm/handlers/BlockHandler.ts, mitm/handlers/HeadersHandler.ts, mitm/handlers/RequestSession.ts, package.build.json, package.json, website/package.json, yarn.lock
This PR modifies User Profiles so they can be restored in a far shorter period, and don't interfere with file chooser popups. Something about loading more than one site prior to load is causing the file picker to stop working. It's unclear what the root issue is. It appears to be in Chrome - something is causing the execution contexts to get out of sync and have the wrong domains (ie, it will still say domain1 while the page is loaded to about:blank)
Closes #452 and #428
=> User Profile Fixes to address FileChooser interference and performance 
