.gitignore
website/gridsome.server.js
website/src/main.js

Now that tsc is building js files into build/, we can remove some of the .gitignore lines. Doing so highlighted the fact that two needed website js files were being excluded.

fix: .gitignore was ignoring files that were needed for website

---

package.build.json
replay-api/endpoints/fetchResource.ts
replay-api/endpoints/fetchSessionMeta.ts
replay-api/lib/SessionLoader.ts
replay-app/backend/ReplayApi.ts
session-state/lib/SessionDb.ts
yarn.lock

Replay api was never closing databases. Also, the API was loading the full session data for every resource that gets loaded.

fix(replay): fix replay api usage

---

core/lib/LocationTracker.ts
core/test/location.test.ts
mitm/handlers/CacheHandler.ts
mitm/handlers/HttpRequestHandler.ts
mitm/lib/MitmRequestAgent.ts
mitm/test/http2.test.ts
session-state/models/CommandsTable.ts

1) Location change was still triggering on a new tab if you clicked a new link to get there and it opened in the background
2) Mitm will blow if client push session throws an error
3) Mitm still duplicating cache header

Small bug fixes

---

core-interfaces/IInteractions.ts
core/lib/DomEnv.ts
core/lib/Interactor.ts
core/lib/Tab.ts
core/test/interact.test.ts
injected-scripts/scripts/jsPath.ts
mitm/lib/MitmProxy.ts
puppet-chrome/lib/Mouse.ts
puppet/interfaces/IPuppetInput.ts
puppet/test/Mouse.test.ts
replay/backend/models/ReplayView.ts
session-state/lib/CommandFormatter.ts
session-state/test/domRecorder.test.ts

The PR changes scrolling elements into view to emit wheel events from the mouse

feat(puppet): use mouse wheel events

---

client/interfaces/IAgentDefaults.ts
client/lib/Agent.ts
core-interfaces/IConfigureSessionOptions.ts
core-interfaces/ITabOptions.ts
core/lib/Session.ts
core/lib/Tab.ts
emulate-browsers/base/lib/DomDiffLoader.ts
full-client/test/basic.test.ts
puppet-chrome/lib/BrowserContext.ts
website/docs/BasicInterfaces/Agent.md
website/docs/BasicInterfaces/Handler.md
website/docs/Overview/BasicConcepts.md
website/docs/Overview/Configuration.md

BREAKING CHANGE: renames “renderingOptions” to “blockedResourceTypes”. Default is now “None”
Closes #113

feat: rename renderingOptions => blockedResourceTypes

---

injected-scripts/scripts/jsPath.ts

Very small fix to make an element that is offscreen count as "not-visible"

fix(core): elements offscreen fail isVisible

---

client/lib/Agent.ts
client/lib/CoreTab.ts
client/lib/Tab.ts
commons/eventUtils.ts
core-interfaces/IWaitForElementOptions.ts
core-interfaces/IWaitForOptions.ts
core-interfaces/IWaitForResourceOptions.ts
core/lib/CoreServerConnection.ts
core/lib/LocationTracker.ts
core/lib/Tab.ts
core/test/location.test.ts
full-client/test/waitForLocation.test.ts

Adds options for sinceCommandId and timeoutMs to waitForLocation, waitForLoad, waitForAllContentLoaded and waitForNewTab

feat(core): waitForLocation/Load takes a timeout

---

mitm/lib/Dns.ts
mitm/test/dns.test.ts

- Change dns cache to be globally shared
- Fallback dns goes to nodejs (which uses getaddrinfo) instead of using go resolving. Ideally, we would use this first, but I can't determine by default if this is coming from a local resolution or a dns resolution.

feat(dns): global cache for dns

---

client/lib/ScriptInstance.ts
core/lib/GlobalPool.ts
full-client/test/emulate.test.ts
puppet-chrome/index.ts

Fixes issue where multiple browsers opening headed will close the first one, which shuts everything down.

fix(puppet): launch non-default (83) headed chrome

---

client/lib/Agent.ts
client/lib/CoreSession.ts
commons/Logger.ts
commons/utils.ts
core-interfaces/IAgentMeta.ts
core/lib/CoreServerConnection.ts
core/lib/GlobalPool.ts
core/lib/Session.ts
emulate-browsers/base/lib/modifyHeaders.ts
full-client/test/tab.test.ts
website/docs/BasicInterfaces/Agent.md

feat: print full stack trace for errors
feat: add keep-alive to http1 requets.

feat(client): add ability to get agent metadata

---

replay/backend/Application.ts
replay/index.ts

feat(replay): don’t hang if screen not available

---

.github/workflows/lint-and-test.yml
core/test/user-profile.test.ts
website/blog/2020-12-29-why-handlers.md
website/blog/2021-02-19-chrome-stable.md
website/gridsome.config.js
website/package.json
website/src/pages/Blog.vue
yarn.lock

Add blog post about chrome and atom feed

feat(website): blog post about chrome + atom

---

emulate-humans/ghost/Bezier.ts
emulate-humans/ghost/generateVector.ts

The out of memory error occurring occasionally is coming from NaNs in ghost. Fixed these cases.
NOTE: I can't yet reproduce this failing windows test.

fix(ghost): fix oom error

---

mitm-socket/index.ts
mitm/handlers/BaseHttpHandler.ts
mitm/handlers/HeadersHandler.ts
mitm/handlers/HttpRequestHandler.ts
mitm/lib/MitmRequestAgent.ts
mitm/lib/MitmRequestContext.ts
mitm/lib/Utils.ts

- Reduce log level of some errors in the mitm.
- Catches errors thrown from http2push rejections
- chore: refactor small portion of mitm to make it easier to follow

fix(mitm): empty headers bug, clean errors

---

client/connections/ConnectionToCore.ts
client/lib/CoreCommandQueue.ts
client/lib/Handler.ts
commons/Queue.ts
core/index.ts
full-client/test/handler.test.ts

fix(client): properly handle unhandled disconnect

---

core/dbs/SessionDb.ts
core/models/ResourcesTable.ts
mitm/lib/MitmRequestContext.ts

- Record cached resource status code (was not being copied correctly)

Cached resource

---

website/docs/Advanced/Session.md
website/docs/Overview/Configuration.md

This PR just adds some docs about how to manage session databases.

chore(docs): explain session management

---

core/lib/AwaitedEventListener.ts
core/lib/Session.ts
full-client/test/basic.test.ts
mitm/handlers/BaseHttpHandler.ts
mitm/handlers/HeadersHandler.ts

fix(core): block resources not working

---

core-interfaces/IInteractionsHelper.ts
core/injected-scripts/MouseEvents.ts
core/lib/FrameNavigationsObserver.ts
core/lib/Interactor.ts
core/lib/JsPath.ts
core/lib/MouseoverListener.ts
core/lib/MouseupListener.ts
core/test/interact.test.ts
emulate-humans/ghost/index.ts
emulate-humans/ghost/test/ghost.test.ts
puppet-chrome/lib/Mouse.ts
puppet-interfaces/IPuppetInput.ts
puppet/test/Mouse.test.ts
puppet/test/Page.popups.test.ts
puppet/test/TestPage.ts

Change the way we verify clicks/mouse moves slightly. We had issues under "load" where these commands wouldn't complete in time, so would "timeout" before a "mousemove" was even sent to Chrome.

fix(core): fix failing interact test

---

client/lib/Handler.ts
core/server/ConnectionToClient.ts
full-client/test/handler.test.ts

Resolves some of the comments in #187: we had a scenario where agents would get "assigned" a connection to wait on, but if that connection disconnected, they would fail without a place to catch them and requeue (beyond waitForAllDispatchesSettled).
This PR automatically re-queues any agents that were never "started" on a connection, aka, no side-effects.

Requeue agents assigned to a disconnected connections (if not started).

---

client/package.json
core-interfaces/package.json
core/package.json
full-client/package.json
full-client/test/document.test.ts
website/package.json
yarn.lock

fix(core): allow retrieving datasets

---

client/lib/CoreEventHeap.ts
client/lib/CoreTab.ts
client/lib/Dialog.ts
client/lib/FrozenTab.ts
client/lib/Resource.ts
client/lib/Tab.ts
core/lib/AwaitedEventListener.ts
core/lib/Tab.ts
core/test/events.test.ts
full-client/test/document.test.ts
interfaces/IPuppetDialog.ts
interfaces/IPuppetPage.ts
puppet-chrome/lib/Page.ts
website/docs/BasicInterfaces/Agent.md

Small PR to enable listening for and dismissing javascript dialogs

feat(core): javascript dialog handling

---

client/interfaces/IAwaitedOptions.ts
client/lib/Agent.ts
client/lib/CoreFrameEnvironment.ts
client/lib/CoreTab.ts
client/lib/FileChooser.ts
client/lib/Tab.ts
commons/utils.ts
core/lib/FrameEnvironment.ts
core/lib/Tab.ts
emulate-browsers/base/lib/modifyHeaders.ts
full-client/test/document.test.ts
full-client/test/filechooser.test.ts
interfaces/IFileChooserPrompt.ts
interfaces/IPuppetFrame.ts
interfaces/IPuppetPage.ts
mitm-socket/lib/CertificateGenerator.ts
puppet-chrome/lib/Frame.ts
puppet-chrome/lib/Page.ts
testing/helpers.ts
testing/package.json
website/docs/Advanced/Dialog.md
website/docs/Advanced/FileChooser.md
website/docs/BasicInterfaces/Agent.md
website/docs/BasicInterfaces/Tab.md
website/docs/links.yaml
yarn.lock

This PR adds a waitForFileChooser method to tab and agent.
Closes #237 and #236

feat(core): waitForFileChooser

---

core/lib/Session.ts
core/server/ConnectionToClient.ts
full-client/test/emulate.test.ts
interfaces/IGeolocation.ts
interfaces/IPluginBrowserEmulator.ts
interfaces/IPuppetContext.ts
interfaces/IPuppetPage.ts
interfaces/ISessionCreateOptions.ts
plugins/default-browser-emulator/index.ts
plugins/default-browser-emulator/lib/helpers/setGeolocation.ts
plugins/execute-js/test/basic.test.ts
puppet-chrome/lib/BrowserContext.ts
website/docs/BasicInterfaces/Agent.md

Add ability to set geolocation for an agent.

feat(core): geolocation feature

---

full-client/test/detection.test.ts
full-client/test/emulate.test.ts
plugins/default-browser-emulator/index.ts
plugins/default-browser-emulator/injected-scripts/_proxyUtils.ts
plugins/default-browser-emulator/interfaces/IBrowserData.ts
plugins/default-browser-emulator/lib/loadDomOverrides.ts

This PR fixes some creepjs issues, and some structural changes caused by the plugins that make deviceMemory and enumerated devices rotate per dom environment.

fix(plugins): inconsistent dom env properties

---

core/index.ts
core/injected-scripts/interactReplayer.ts
core/lib/GlobalPool.ts
core/models/SessionLogsTable.ts
core/test/GlobalPool.test.ts
core/test/basic.test.ts
examples/detach.ts
examples/example.org.ts
examples/news.ycombinator.com.ts
examples/proxy-example.mjs
examples/show-browser.js
fullstack/index.cjs
fullstack/index.ts
plugin-utils/lib/BrowserEngine.ts
puppet-chrome/index.ts
puppet/index.ts
puppet/lib/launchProcess.ts

- Fix issue with windows tests start and stopping core in same process
- Rename browser-with-no-open-windows event
- Fix blank windows opening in windows headed (Fixes #296)

fix(core): fix windows shutdown, blank cli

---

client/lib/Agent.ts
client/lib/Handler.ts
client/lib/Tab.ts
client/test/handler.test.ts
core/index.ts
core/lib/DevtoolsPreferences.ts
core/lib/GlobalPool.ts
core/lib/Session.ts
core/lib/Tab.ts
core/models/SessionLogsTable.ts
core/test/GlobalPool.test.ts
core/test/basic.test.ts
interfaces/IDevtoolsSession.ts
interfaces/IPuppetBrowser.ts
mitm-socket/lib/CertificateGenerator.ts
mitm/lib/Http2SessionBinding.ts
mitm/lib/MitmRequestAgent.ts
plugin-utils/lib/BrowserEngine.ts
puppet-chrome/index.ts
puppet-chrome/lib/Browser.ts
puppet-chrome/lib/BrowserContext.ts
puppet-chrome/lib/Page.ts
puppet/index.ts
puppet/lib/launchProcess.ts

Pulling a few fixes over from here development until people can make the switch:
- Fix chrome.exe popup (Closes #296)
- Plugins in handlers work (Closes #305) 
- Fixes certgenerator crashing when messages go away (Closes #309)
- Fixes http2 goaway issues (Closes #311)
- Handles some cases of chrome not closing (Some fixes for #312 - keep monitoring)
- Save devtools preferences for headed.

Pull fixes from Hero

---

plugins/default-browser-emulator/injected-scripts/HTMLIFrameElement.prototype.ts

Causing infinite loop on serialization
Closes: #329

fix: Iframe ContentWindow not resolving

---

core/injected-scripts/domStorage.ts
core/test/user-profile.test.ts

fix(user-profile): handle empty database

---

mitm-socket/lib/CertificateGenerator.ts
mitm/lib/MitmProxy.ts

fix(mitm): handle certs resolving before set

---

mitm/handlers/HeadersHandler.ts
mitm/handlers/HttpRequestHandler.ts

fix(mitm): clean invalid response characters

---

client/lib/Agent.ts
client/lib/CoreTab.ts
client/lib/FrozenTab.ts
client/lib/Tab.ts

fix(client): reload should return a resource

---

core/package.json
mitm/handlers/HeadersHandler.ts
mitm/package.json
puppet-chrome/lib/BrowserContext.ts
puppet/test/BrowserContext.test.ts
replay/package.json
website/package.json
yarn.lock

HTTP Cookies that applied to all subdomains ('.twitter.com') were incorrectly being filtered out when getting cookies for a domain.
Fix for #466

Cookie fix
